[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#8B0000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#262730"

[client]
showErrorDetails = false