[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#D4AF37"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#2D1B3D"
textColor = "#F5F5DC"
base = "dark"

[client]
showErrorDetails = false